services:
  sourceverifier:
    restart: unless-stopped
    build: .
    env_file: '.env'
    ports:
      - "${PORT}:${PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # volumes:
    #   - ${CHROMIUM_BROWSER_LOCATION}:/app/chromium-browser