services:
  sourceverifier:
    restart: unless-stopped
    build: .
    env_file: '.env'
    ports:
      - "${PORT}:${PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${KEY_LOCATIONS}:/app/keys/