import dotenv from 'dotenv';

dotenv.config();

const {
  E621_USERNAME, E621_API_KEY, PORT, SECURE, PRIVATE_KEY_LOCATION, CERTIFICATE_LOCATION, CHAIN_LOCATION,
  MONGO_DB_URL, MONGO_DB_NAME, FLARE_SOLVERR_URL, CHROME_EXECUTABLE_LOCATION, BLUESKY_USERNAME, BLUESKY_PASSWORD,
  INKBUNNY_USERNAME, INKBUNNY_PASSWORD, REDDIT_COOKIE, WEASYL_API_KEY, PIXIV_REFRESH_TOKEN,
  PROXY_URI, PROXY_USERNAME, PROXY_PASSWORD
} = process.env;

export const config = {
  E621_USERNAME,
  E621_API_KEY,
  PORT: parseInt(PORT as string),
  SECURE: SECURE == 'true',
  USER_AGENT: 'Janitor Source Verifier/2.0 (by Tarrgon)',
  PRIVATE_KEY_LOCATION,
  CERTIFICATE_LOCATION,
  CHAIN_LOCATION,
  MONGO_DB_URL,
  MONGO_DB_NAME,
  FLARE_SOLVERR_URL,
  CHROME_EXECUTABLE_LOCATION,
  BLUESKY_USERNAME,
  BLUESKY_PASSWORD,
  INKBUNNY_USERNAME,
  INKBUNNY_PASSWORD,
  REDDIT_COOKIE,
  WEASYL_API_KEY,
  PIXIV_REFRESH_TOKEN,
  PROXY_URI,
  PROXY_USERNAME,
  PROXY_PASSWORD
};

for (const [key, val] of Object.entries(config)) {
  if (val === undefined) {
    throw new Error(`${key} is undefined in config`);
  }
}